test-netcdf:
	/bin/bash test_netcdf.bsh

test-hdf4:
	/bin/bash test_hdf4.bsh

test-hdf5:
	/bin/bash test_hdf5.bsh

all:
	( /bin/bash test_netcdf.bsh )
	( /bin/bash test_hdf4.bsh )
	( /bin/bash test_hdf5.bsh )
