
FC=gfortran
FC_CFLAGS=
FC_LFLAGS= 

ARCHIVER=ar
ARCHIEVER_FLAGS= -crvs

# config for F90GIO installation
F90GIO_DIR=/home/cda/Documents/model/F90GIO-fortran
F90GIO_LIB_DIR=$(F90GIO_DIR)/lib
F90GIO_INCLUDE_DIR=$(F90GIO_DIR)/include

# config for Netcdf
NC_CFLAGS=-I/home/cda/Documents/model/netcdf-fortran-4.4.4-gfortran/include
NC_LFLAGS=-L/home/cda/Documents/model/netcdf-fortran-4.4.4-gfortran/lib -lnetcdff -L/home/cda/Documents/model/netcdf-4.4.1.1-gcc/lib -lnetcdf -lnetcdf

# config for HDF4 
H4_CFLAGS=-I/home/cda/Documents/model/hdf-4.2.12-gfortran/include
H4_LFLAGS=-L/home/cda/Documents/model/zlib-1.2.11-gcc/lib -L/home/cda/Documents/model/jpeg-6b-gcc/lib -L/home/cda/Documents/model/hdf-4.2.12-gfortran/lib -lmfhdf -ldf -ljpeg -lz


# config for HDF4 
H5_CFLAGS=-I/home/cda/Documents/model/hdf5-1.8.18-gfortran/include
H5_LFLAGS=-L/home/cda/Documents/model/hdf5-1.8.18-gfortran/lib /home/cda/Documents/model/hdf5-1.8.18-gfortran/lib/libhdf5hl_fortran.a /home/cda/Documents/model/hdf5-1.8.18-gfortran/lib/libhdf5_hl.a /home/cda/Documents/model/hdf5-1.8.18-gfortran/lib/libhdf5_fortran.a /home/cda/Documents/model/hdf5-1.8.18-gfortran/lib/libhdf5.a -L/home/cda/Documents/model/zlib-1.2.11-gcc/lib -lz -ldl -lm -Wl,-rpath -Wl,/home/cda/Documents/model/hdf5-1.8.18-gfortran/lib
#H5_LFLAGS=-L/home/cda/Documents/model/hdf5-1.8.18-gfortran/lib -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -L/home/cda/Documents/model/zlib-1.2.11-gcc/lib -lz -ldl -lm -Wl,-rpath -Wl,/home/cda/Documents/model/hdf5-1.8.18-gfortran/lib

