
FC=ifort
FC_CFLAGS= -warn
FC_LFLAGS=

ARCHIVER=ar
ARCHIEVER_FLAGS= -crvs

# config for F90GIO installation
F90GIO_DIR=/Users/cda/Documents/work/pkg/model/F90GIO-ifort
F90GIO_LIB_DIR=$(F90GIO_DIR)/lib
F90GIO_INCLUDE_DIR=$(F90GIO_DIR)/include

# config for Netcdf
NC_CFLAGS=-I/Users/cda/Documents/work/pkg/model/netcdf-fortran-4.4.4-ifort/include
NC_LFLAGS=-L/Users/cda/Documents/work/pkg/model/netcdf-fortran-4.4.4-ifort/lib -lnetcdff -L/Users/cda/Documents/work/pkg/model/netcdf-4.4.1.1-gcc/lib -lnetcdf -lnetcdf 

# config for HDF4 
H4_CFLAGS=-I/Users/cda/Documents/work/pkg/model/hdf-4.2.12-ifort/include
H4_LFLAGS=-L/Users/cda/Documents/work/pkg/model/zlib-1.2.11-gcc/lib -L/Users/cda/Documents/work/pkg/model/jpeg-6b-gcc/lib -L/Users/cda/Documents/work/pkg/model/hdf-4.2.12-ifort/lib -lmfhdf -ldf -ljpeg -lz


# config for HDF4 
H5_CFLAGS=-I/Users/cda/Documents/work/pkg/model/hdf5-1.8.18-ifort/include
#H5_LFLAGS=-L/Users/cda/Documents/work/pkg/model/hdf5-1.8.18-ifort/lib /Users/cda/Documents/work/pkg/model/hdf5-1.8.18-ifort/lib/libhdf5hl_fortran.a /Users/cda/Documents/work/pkg/model/hdf5-1.8.18-ifort/lib/libhdf5_hl.a /Users/cda/Documents/work/pkg/model/hdf5-1.8.18-ifort/lib/libhdf5_fortran.a /Users/cda/Documents/work/pkg/model/hdf5-1.8.18-ifort/lib/libhdf5.a -L/Users/cda/Documents/work/pkg/model/zlib-1.2.11-gcc/include -lz -ldl -lm

H5_LFLAGS=-L/Users/cda/Documents/work/pkg/model/hdf5-1.8.18-ifort/lib  -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -L/Users/cda/Documents/work/pkg/model/zlib-1.2.11-gcc/include -lz -ldl -lm
