name: build_gfortran

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  cmake_build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: "install NetCDF, HDF4, HDF5"
      run: |
           sudo apt-get update
           sudo apt install cmake -y
           sudo apt install gfortran -y
           sudo apt install libnetcdf-dev libnetcdff-dev netcdf-bin  -y
           sudo apt install hdf4-tools libhdf4-dev -y
           sudo apt install hdf5-tools libhdf5-dev -y
           ulimit -s unlimited

    - name: "check version and envs"
      run: |
           echo "===============================" && nf-config --all
           echo "===============================" && nc-config --all
           echo "===============================" && gcc -v
           echo "===============================" && gfortran -v
           echo "===============================" && pwd
           echo "===============================" && h4fc --version && h4fc -show test.f90
           echo "===============================" && h5fc -showconfig && h5fc -show test.f90
           echo "===============================" && ulimit -a

    - name: "cmake build"
      run: |
           source ./config/env.gnu.github.sh
           cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_Fortran_COMPILER=gfortran -DBUILD_H4=ON -DBUILD_H5=ON -DH5_VERSION_1_8=OFF -DBUILD_NC=ON  -DBUILD_FAST_IO=ON -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE=ON
           cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: "cmake test"
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure 

    - name: "cmake install"
      working-directory: ${{github.workspace}}/build
      run: |
           make install
           ls -al ${{github.workspace}}/install/*

    - name: "build using the F90GIO lib"
      run: |
           mkdir ${{github.workspace}}/test-external && cd ${{github.workspace}}/test-external
           source ${{github.workspace}}/config/env.gnu.github.sh
           ln -sf ${{github.workspace}}/test-fast/* .
           echo "${NC_LIBS}"
           echo "${NC_INCLUDE}"
           echo "${H5_LIBS}"
           echo "${H5_INCLUDE}"
           gfortran -I${{github.workspace}}/install/include -I${NC_INCLUDE}  -c test_ncio.f90
           gfortran test_ncio.o -o test_ncio.x -L${{github.workspace}}/install/lib -lncio ${NC_LIBS}

           gfortran -I${{github.workspace}}/install/include -I${H5_INCLUDE} -c test_h5io.f90
           gfortran test_h5io.o -o test_h5io.x -L${{github.workspace}}/install/lib -lh5io ${H5_LIBS}

           ls -al *.x

           ./test_ncio.x | grep "Test passed" && echo "success" || exit 1
           ./test_h5io.x | grep "Test passed" && echo "success" || exit 1
