name: build_gfortran

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  cmake_build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: "install NetCDF"
      run: |
           sudo apt install libnetcdf-dev libnetcdff-dev netcdf-bin hdf4-tools libhdf4-dev
           ulimit -s unlimited

    - name: "check version and envs"
      run: |
           echo "===============================" && nf-config --all
           echo "===============================" && nc-config --all
           echo "===============================" && gcc -v
           echo "===============================" && gfortran -v
           echo "===============================" && pwd
           echo "===============================" && h4fc --version && h4fc -show test.f90
           echo "===============================" && ulimit -a

    - name: "cmake build (build NetCDF, HDF4)"
      run: |
           source ./config/env.gnu.github.sh
           cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_Fortran_COMPILER=gfortran -DBUILD_H4=on -DBUILD_H5=off -DBUILD_NC=on -DTEST_FULL=off -DCMAKE_VERBOSE_MAKEFILE=off
           cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: "cmake test"
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure 


